GET http://localhost:3000/tweets

###

POST http://localhost:3000/tweets
Content-Type: application/json

{
    "Text": "Esse é um tweet...",
    "User": {
        "Name": "Eric Batista"
    }
}

###

GET http://localhost:3000/mail-list

###

POST http://localhost:3000/mail-list
Content-Type: application/json

{
    "Emails": ["user1@test.com", "user2@test.com", "user3@test.com"]
}
